### ISSUE TITLE
Full documentation link is broken

### ISSUE THREAD

**Issue by tobang** [cfeenstra1024/kamstrup-multical-hardware#2]
@cfeenstra1024 The link to the full documentation is broken. Do you have any idea, when the PR will be merged.

**Comment by cfeenstra1024** [comment]
Hi @tobang, 
I've updated the [documentation link](https://deploy-preview-3513--esphome.netlify.app/components/sensor/kamstrup_kmp). 
The updated documentation describes all features of the actual implementation that should become part of ESPHome. You can run this if you setup the development environment yourself. The option using the external component does also work, but is less fancy and does not support custom sensors. Please check the example config file for information about how to configure the external component, including the sensors it should expose.

Note: the hardware is the same for both. 

Unfortunately, I have no idea when this will become available in the official ESPHome. I can write the component, but others are responsible for merging the new code into the ESPHome release.

**Comment by tobang** [comment]
Thank you, much appreciated. I will try to make it work with the external component method.

**Comment by cfeenstra1024** [comment]
@tobang FYI: the Kamstrup component is now available in ESPHome version 2024.3.0
